Feature/build for macos
homuler/MediaPipeUnityPlugin pull request #25
Opened 2020-11-27 15:50 UTC by SergeyAME

Fix for issue #22 .
Now you can build a project for the OS X (CPU version).

- Added target for OS X.
- Fixed problems with resolution of WebCamTexture.

2020-12-01 10:15 UTC, homuler requested changes

2020-12-01 10:15 UTC, homuler commented on Assets/MediaPipe/Examples/Scripts/WebCamScreenController.cs
> +    return webCamTexture.width > TEXTURE_SIZE_THRESHOLD;
I think it is better to check whether the size is set correctly.

```cs
return webCamTexture.width == DefaultWidth && webCamTexture.height == DefaultHeight;
```

2020-12-01 10:15 UTC, homuler commented on Assets/MediaPipe/Examples/Scripts/WebCamScreenController.cs
> +    return webCamTexture == null ? false : webCamTexture.isPlaying && IsWebCamTextureInitialized();
I think `IsWebCamTextureInitialized` should check whether `webCamTexture` is null or not.

```cs
public bool IsPlaying() {
  return IsWebCamTextureInitialized() && webCamTexture.isPlaying;
}
```

2020-12-01 10:15 UTC, homuler commented on Assets/MediaPipe/Examples/Scripts/WebCamScreenController.cs
> +  {
[nits] I know that K&R style is preferred in C#, but will you change it like this?

```cs
public void InitScreen() {
   ...
}
```

2020-12-01 10:15 UTC, homuler commented on Assets/MediaPipe/Examples/Scripts/WebCamScreenController.cs
> +  }
Please insert a new line here.

2020-12-01 10:15 UTC, homuler commented on Assets/MediaPipe/Examples/Scripts/SceneDirector.cs
> +  const int MAX_WAIT_FRAME = 500;
[ask] On average (or at worst case), how many frames does it take for the camera to be initialized?

2020-12-01 10:15 UTC, homuler commented on Assets/MediaPipe/Examples/Scripts/WebCamScreenController.cs
> -    Renderer renderer = GetComponent<Renderer>();
[ask] Will you tell me why those steps should be deferred?

2020-12-01 10:15 UTC, homuler commented on Makefile
> +bazel_common_target := $(bazel_models_target) $(bazel_protos_target) --cxxopt='-std=c++14'
Please configure it in [.bazelrc](https://github.com/homuler/MediaPipeUnityPlugin/blob/master/C/.bazelrc).
This may break android build.

cf. https://github.com/google/mediapipe/blob/master/.bazelrc#L25

2020-12-01 10:36 UTC, SergeyAME commented on Assets/MediaPipe/Examples/Scripts/WebCamScreenController.cs
> +    return webCamTexture.width > TEXTURE_SIZE_THRESHOLD;
I'm not sure that it will be work in all cases. For example when you request DefaultWidth = **480**, webCamTexture return **640** (at least at OS X). If you request DefaultWidth = 640, it return 640. 

p.s. also code will crash in that point and other, if requested resolution is not supported (for example i request full HD, but my web cam support only HD. I think it doesn't matter at current moment, because as i understand you completely change the way like SDK will work with webCamTexture and pixels.

2020-12-01 10:45 UTC, SergeyAME commented on Assets/MediaPipe/Examples/Scripts/SceneDirector.cs
> +  const int MAX_WAIT_FRAME = 500;
For my laptop in average it takes 300 frames.

2020-12-01 10:53 UTC, SergeyAME commented on Assets/MediaPipe/Examples/Scripts/WebCamScreenController.cs
> -    Renderer renderer = GetComponent<Renderer>();
I moved creating outputTexture to separate method, because for creating outputTexture we must know width and height of webCamTexture. In your code you use DefaultWidth and DefaultHeight, but i start to use actual width & height from webCamTexture. At that point (immediately after calling the play method for webCamTexture) webCamTexture return "wrong" values 16x16. We can get correct values from webCamTexture only after it will be initialized.

2020-12-01 11:04 UTC, homuler commented on Assets/MediaPipe/Examples/Scripts/WebCamScreenController.cs
> +    return webCamTexture.width > TEXTURE_SIZE_THRESHOLD;
> For example when you request DefaultWidth = 480, webCamTexture return 640 (at least at OS X). If you request DefaultWidth = 640, it return 640.

Yes, because the real value is set in each `.unity` file (those values are overwritten).

2020-12-01 11:12 UTC, homuler commented on Assets/MediaPipe/Examples/Scripts/WebCamScreenController.cs
> -    Renderer renderer = GetComponent<Renderer>();
OK, then please initialize `pixelData` at the same time as `outputTexture`.

> In your code you use DefaultWidth and DefaultHeight, but i start to use actual width & height from webCamTexture. 

I think it already does, and please initialize `pixelData` as it is.
```cs
pixelData = new Color32[webCamTexture.width * webCamTexture.height];
```

2020-12-01 11:18 UTC, homuler commented on Assets/MediaPipe/Examples/Scripts/WebCamScreenController.cs
> +    webCamTexture = new WebCamTexture(device?.name, DefaultWidth, DefaultHeight, FPS);
Please rather merge master, not cherry-pick.
Some additional diffs are included now.

2020-12-01 11:23 UTC, SergeyAME commented on Assets/MediaPipe/Examples/Scripts/WebCamScreenController.cs
> +    return webCamTexture.width > TEXTURE_SIZE_THRESHOLD;
I understand, that real value come from .unity file, and values from code will be overwritten :) I'm talking about the values that WebCamTexture returns at runtime after we have passed our values (overwritten by .unity)  to the WebCamTexture constructor.

Look at the screen, that was done from debug view in studio.
<img width="408" alt="Screenshot 2020-12-01 at 13 29 13" src="https://user-images.githubusercontent.com/74453846/100734356-97f46800-33e0-11eb-8678-419dfa263674.png">

2020-12-01 11:24 UTC, homuler commented on Makefile
> +	rm -f $(plugindir)/libmediapipe_c.bundle
maybe `libmediapipe_c.dylib` ?

2020-12-01 11:31 UTC, SergeyAME commented on Makefile
> +	rm -f $(plugindir)/libmediapipe_c.bundle
dumb... sry.

2020-12-01 11:42 UTC, homuler commented on Assets/MediaPipe/Examples/Scripts/WebCamScreenController.cs
> +    return webCamTexture.width > TEXTURE_SIZE_THRESHOLD;
Thank you. Now I see.
Hmm...certainly it looks that the value cannot be predicted (https://docs.unity3d.com/ScriptReference/WebCamTexture-requestedHeight.html).

Will you change the comment like this? (if you use MacBook pro).
In fact, I'm not sure if it is OS X's problem (the camera may causes the issue).

```cs
// Some cameras may take time to be initialized, so wait here. (e.g. on MacBook Pro, the size of webCamTexture is 16x16 at the beginning.)
```

2020-12-01 12:28 UTC, SergeyAME commented on Assets/MediaPipe/Examples/Scripts/WebCamScreenController.cs
> +    return webCamTexture.width > TEXTURE_SIZE_THRESHOLD;
I think problem are more common. I came across several topics where people are faced with getting the correct dimensions for the texture. Just for example:
https://answers.unity.com/questions/232168/how-can-i-get-the-device-camera-aspect-ratio.html?_ga=2.132976206.1384449721.1606825289-1204939603.1605516746
https://answers.unity.com/questions/773464/webcamtexture-correct-resolution-and-ratio.html#answer-1148424

You don't have that problem on your device?
Of course i can change comment, but i don't sure that it will be right :)

2020-12-01 12:32 UTC, SergeyAME commented on Assets/MediaPipe/Examples/Scripts/WebCamScreenController.cs
> +    return webCamTexture.width > TEXTURE_SIZE_THRESHOLD;
Done.

2020-12-01 12:37 UTC, homuler commented on Assets/MediaPipe/Examples/Scripts/WebCamScreenController.cs
> +    return webCamTexture.width > TEXTURE_SIZE_THRESHOLD;
> I think problem are more common.

I completely agree with you. That's why I would not like to particularly refer to OS X here.

> You don't have that problem on your device?

Well, not yet for better or worse.

2020-12-02 15:01 UTC, homuler approved these changes
Thank you! LGTM

2020-12-02 15:01 UTC, merged