Fix high resolution camera performance on mobile by allowing a default resolution
homuler/MediaPipeUnityPlugin pull request #347
Opened 2021-11-08 12:19 UTC by ROBYER1

Use a manually set default resolution within 300px to choose the nearest default resolution on mobile. Is auto-selected if the value matches or if it is within the 300px range
-Prevents huge performance issues on phones with high resolution cameras when using the sample app

2021-11-08 12:45 UTC, homuler requested changes

2021-11-08 12:45 UTC, homuler commented on Assets/Mediapipe/Samples/Common/Scripts/ImageSource/ImageSource.cs
> +    [Header("This resolution will be matched within 300px if override is true")]
Please always use `LF` as a new line character, not `CR+LF`.
The same goes for the other parts.

2021-11-08 12:45 UTC, homuler commented on Assets/Mediapipe/Samples/Common/Scripts/ImageSource/WebCamSource.cs
> +        //Flipped around if on mobile
Insert a space character after `//`.

```suggestion
        // Flipped around if on mobile
```

The same goes for the other parts.

2021-11-08 12:45 UTC, homuler commented on Assets/Mediapipe/Samples/Common/Scripts/ImageSource/ImageSource.cs
> +    public bool overrideDefaultResolution = true;
I don't like to unnecessarily increase the number of options.
Make sure that the best resolution is always selected from `availableResolutions`.

2021-11-08 12:45 UTC, homuler commented on Assets/Mediapipe/Samples/Common/Scripts/ImageSource/ImageSource.cs
> +    public ImageSource.ResolutionStruct defaultRes;
```suggestion
    // For the default resolution, the one whose width is closest to this value will be chosen.
    [SerializeField] private int preferableDefaultWidth = 1280;
```

2021-11-08 12:45 UTC, homuler commented on Assets/Mediapipe/Samples/Common/Scripts/ImageSource/WebCamSource.cs
> +      defaultRes.width = defaultHeight;
Align the indentation.
The same goes for the other parts.

2021-11-08 13:28 UTC, ROBYER1 reviewed
Thanks for the change suggestions - I learnt some good practices for PRs here also which I will use in future when making PRs. If you need any explicit changes to this, let me know!

2021-11-09 11:11 UTC, homuler requested changes

2021-11-09 11:11 UTC, homuler commented on Assets/Mediapipe/Samples/Common/Scripts/ImageSource/ImageSource.cs
> +    [SerializeField] public int preferableDefaultWidth = 1280;
Currently this value is only used by `WebCamSource`, so define there.
```diff
diff --git a/Assets/Mediapipe/Samples/Common/Scripts/ImageSource/WebCamSource.cs b/Assets/Mediapipe/Samples/Common/Scripts/ImageSource/WebCamSource.cs
index d59aeea..7b4cf99 100644
--- a/Assets/Mediapipe/Samples/Common/Scripts/ImageSource/WebCamSource.cs
+++ b/Assets/Mediapipe/Samples/Common/Scripts/ImageSource/WebCamSource.cs
@@ -19,6 +20,8 @@ namespace Mediapipe.Unity
   {
     private const string _TAG = nameof(WebCamSource);
 
+    // For the default resolution, the one whose width is closest to this value will be chosen.
+    [SerializeField] private int _preferableDefaultWidth = 1280;
     [SerializeField] private ResolutionStruct[] _defaultAvailableResolutions;
 
     private static readonly object _PermissionLock = new object();
```

2021-11-09 11:11 UTC, homuler commented on Assets/Mediapipe/Samples/UI/Scripts/ImageSourceConfig.cs
> +      bool resolutionFound = false;
I think you don't need to modify this file, because `ImageSource#SelectSource` will select default resolution automatically.

2021-11-09 13:42 UTC, ROBYER1 commented
Updated now only WebCamSource does the switching, the only outstanding issue I can see (other than me hopefully finally sorting the .cs scripts to be lf not crlf - sorry about that!) is that the resolution dropdown in the config menu doesn't actually show the current resolution being used

2021-11-09 14:11 UTC, homuler commented on Assets/Mediapipe/Samples/Common/Scripts/ImageSource/WebCamSource.cs
>        return (resolutions == null || resolutions.Length == 0) ? new ResolutionStruct() : resolutions[0];
This is not fixed yet.

2021-11-09 14:12 UTC, homuler commented
> Wondering what is the best way to approach that?

Revert all the changes in ImageSourceConfig.cs
https://github.com/homuler/MediaPipeUnityPlugin/pull/347/files#diff-e59ac127e792a73fca8e43e5201c656b7eb7f23e40684d0ed549ea4a40aa2e3a

2021-11-09 14:18 UTC, ROBYER1 commented on Assets/Mediapipe/Samples/Common/Scripts/ImageSource/WebCamSource.cs
>        return (resolutions == null || resolutions.Length == 0) ? new ResolutionStruct() : resolutions[0];
Thanks just tested it and pushed it too

2021-11-09 14:24 UTC, ROBYER1 commented
All sorted there now, if there is anything else needing to be changed on this, let me know. I'm going to get back to looking into the [graph latency issue](https://github.com/homuler/MediaPipeUnityPlugin/issues/302) this week but I'm pretty stumped  with that as I'm still learning how the new sample app works.

2021-11-09 15:03 UTC, homuler requested changes
Thanks. I think we're almost there.

2021-11-09 15:03 UTC, homuler commented on Assets/Mediapipe/Samples/Common/Scripts/ImageSource/WebCamSource.cs
> +    // For the default resolution, the one whose width is closest to this value will be chosen.
[imo] If you use `Header` or `Tooltip`, I think you should describe what you wrote in your comment.

```suggestion
    [Tooltip("For the default resolution, the one whose width is closest to this value will be chosen")]
```

2021-11-10 02:04 UTC, homuler approved these changes
Thanks!
LGTM

2021-11-10 02:08 UTC, merged